### ISSUE TITLE
pod install warning error: "No podspec file was found" and running error.

### ISSUE THREAD

**Issue by RohanSensei** [theweavrs/rn-admob#4]
> [!] use_native_modules! skipped the react-native dependency 'rn-admob'. No podspec file was found.

then run error:
> Unhandled JS Exception: Requiring module "node_modules/rn-admob/RNAdMobRewarded.js", which threw an exception: Invariant Violation: Native module cannot be null.
ExceptionsManager.js:94
Unhandled JS Exception: TypeError: TypeError: Cannot read property 'default' of undefined

rn: 0.60.3
"rn-admob": "^1.0.3"

**Comment by helloimfrog** [comment]
Can you show here your Podfile?! :/

**Comment by RohanSensei** [comment]
autolinking, so I didn't edit the pod file.

platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'yi2' do
  # Pods for yi2
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

  target 'yi2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'yi2-tvOS' do
  # Pods for yi2-tvOS

  target 'yi2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

**Comment by helloimfrog** [comment]
Add `pod 'RNAdMobManager', :path => '../node_modules/rn-admob'` to your Podfile and run `pod install`

**Comment by RohanSensei** [comment]
> [!] No podspec found for `RNAdMobManager` in `../node_modules/rn-admob`

more of the logs:
> Analyzing dependencies
Fetching podspec for `RNAdMobManager` from `../node_modules/rn-admob`
[!] No podspec found for `RNAdMobManager` in `../node_modules/rn-admob`

> [!] use_native_modules! skipped the react-native dependency 'rn-admob'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a good example of a package.json
    driven podspec. See https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library

**Comment by helloimfrog** [comment]
Do you find `RNAdMobManager.podspec` in `node_modules/rn-admob`??

**Comment by RohanSensei** [comment]
> Do you find `RNAdMobManager.podspec` in `node_modules/rn-admob`??

no

**Comment by RohanSensei** [comment]
I removed the package and yarn add rn-admob again, the issue remains.

**Comment by helloimfrog** [comment]
You can try the following step:
1. Remove `Podfile.lock` and `Pods` folder in `ios`
2. Reinstall all lib by the following commands:
```
rm -rf node_modules
rm yarn.lock
yarn cache clean
yarn install
react-native link rn-admob
```
3. `cd ios` and run `pod install`

**Comment by RohanSensei** [comment]
you suggest I link the lib? but the rn version > 0.60

**Comment by helloimfrog** [comment]
Just do it man! ;) I've tried it before.
Autolinking is not support some libraries and i think this lib is one of them :v

**Comment by RohanSensei** [comment]
I did all above, after linked the lib, podfile not changed.
and when I debug, the app crashes with errors below:
> 无法进行调试。执行命令 react-native run-ios --simulator --no-packager --verbose 时出错: 执行命令 react-native run-ios --simulator --no-packager --verbose 时出错 (error code 101)

Then I unlink this lib, everything back to the situations before

**Comment by RohanSensei** [comment]
@Long2k1708 thank u for the patience, I'd like to init a new project and try this lib again.

**Comment by thecodrr** [comment]
@RohanSensei what are the results? Is it working for you?
