### ISSUE TITLE
 module 'GoogleMobileAds' not found on react-native 0.60.4

### ISSUE THREAD

**Issue by zkerkeb** [theweavrs/rn-admob#5]
hi, i'm having trouble installing this package,

I followed the Readme instructions,

I added ```pod 'Google-Mobile-Ads-SDK'``` to my podfile so GoogleMobileAds should be recognized,

I Removed podfiles and reinstalled them several times but it always show this message when I try to launch my app on the simulator.

Those files are concerned : 

- RNGADBannerView.m
- RCTConvert+GADAdSize.m
- RNAdMobInterstitial.m
- RNAdMobRewarded.h:

Do you have some solution i could try to fix this error? 

Thank you !

Edit: I forgot to mention it happens on Ios, did not try yet on android.

**Comment by zkerkeb** [comment]
I managed to make it work by doing this step:

Double-click to Pods project, select RNAdMobManager in TARGET, click Build Phases, expand Link Binary With Libraries, drag GoogleMobileAds.framework from Pods > Pods > Google-Mobile-Ads-SDK to Link Binary With Libraries you have expanded before.

to recap I just installed the package and did the step below to make it works,

Hope it helps someone.

**Comment by andreiciceu** [comment]
It'd be nice to be added automatically
