### ISSUE TITLE
Android app crashes on startup

### ISSUE THREAD

**Issue by smakosh** [theweavrs/rn-admob#7]
## Libraries
```
"react-native": "^0.60.5",
"react-native-google-admob": "https://github.com/thecodrr/react-native-google-admob",
```

**Comment by Spacarar** [comment]
make sure you have added your app id to the AndroidManifest.xml. That was my issue.
https://github.com/thecodrr/react-native-google-admob#android

**Comment by smakosh** [comment]
I did

**Comment by Spacarar** [comment]
Maybe the id is invalid?

have you tried the test id?`ca-app-pub-3940256099942544~1458002511` didn't realize I copied this from the iOS setup documentation https://developers.google.com/admob/ios/quick-start but it worked for my app.

**Comment by smakosh** [comment]
I removed the package and surprisingly the android app is still crashing on startup, going to start all over and move the codebase to the new RN project, closing this until I'm sure it is caused by this package.

**Comment by smakosh** [comment]
I confirm that after installing this package again, the app crashes, the id isn't invalid.

**Comment by thecodrr** [comment]
@smakosh Can you please do `adb logcat > logcat.log` with your device/emulator connected? Make sure to open the app and wait until it crashes and then press `CTRL + C`. Then upload/copy-paste the contents of `logcat.log` file here.

**Comment by smakosh** [comment]
I installed the other package (main repository) & linked it manually & it's working well

**Comment by thecodrr** [comment]
@smakosh Can you send the logcat output? This is a similar problem to #6 but it's specific to a factor I don't know about. Hopefully, if you send the output of `logcat`, I can debug and fix the issue.
