### ISSUE TITLE
which version of the dependency was updated in in build.gradle. which version is Google Play Services used?

### ISSUE THREAD

**Issue by 123dma** [theweavrs/rn-admob#9]
I tried to see some files, but they are locked. I think there should be no locked files.

Thank´s

**Comment by Rob2k9** [comment]
There are no locked files here at all so i have no idea what your doing 

you can find the information you need here

https://github.com/thecodrr/react-native-google-admob/blob/master/android/build.gradle

it clearly shows play-services-ads:17.2.1

**Comment by thecodrr** [comment]
I am using `17.2.1` version because it is the most stable compared to `18+` and runs well on both AndroidX & non-AndroidX devices.
